# Generated by Django 3.0.3 on 2020-05-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_content_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='status',
            field=models.CharField(choices=[('Evet', 'Evet'), ('Hayır', 'Hayır')], max_length=10),
        ),
    ]
